version: '2'
services:
    testcentauri-app:
        image: testcentauri
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://testcentauri-postgresql:5432/TestCentauri
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    testcentauri-postgresql:
        extends:
            file: postgresql.yml
            service: testcentauri-postgresql
